use {
  crate::raylib::bindings::{
    CameraMode_CAMERA_CUSTOM, CameraMode_CAMERA_FIRST_PERSON, CameraMode_CAMERA_FREE,
    CameraMode_CAMERA_ORBITAL, CameraMode_CAMERA_THIRD_PERSON, CameraMoveForward, CameraMoveRight,
    CameraMoveUp, CameraProjection_CAMERA_ORTHOGRAPHIC, CameraProjection_CAMERA_PERSPECTIVE,
    ClearBackground, CloseWindow, Color as RaylibColor, DEG2RAD, DisableCursor, DrawCube,
    DrawCubeWires, DrawGrid, DrawModel, DrawText, EnableCursor, EndDrawing, EndMode3D,
    GetCurrentMonitor, GetMonitorRefreshRate, GetMouseWheelMove, GetMouseWheelMoveV, InitWindow,
    IsKeyDown, KeyboardKey_KEY_A, KeyboardKey_KEY_APOSTROPHE, KeyboardKey_KEY_B,
    KeyboardKey_KEY_BACK, KeyboardKey_KEY_BACKSLASH, KeyboardKey_KEY_BACKSPACE, KeyboardKey_KEY_C,
    KeyboardKey_KEY_CAPS_LOCK, KeyboardKey_KEY_COMMA, KeyboardKey_KEY_D, KeyboardKey_KEY_DELETE,
    KeyboardKey_KEY_DOWN, KeyboardKey_KEY_E, KeyboardKey_KEY_EIGHT, KeyboardKey_KEY_END,
    KeyboardKey_KEY_ENTER, KeyboardKey_KEY_EQUAL, KeyboardKey_KEY_ESCAPE, KeyboardKey_KEY_F,
    KeyboardKey_KEY_F1, KeyboardKey_KEY_F2, KeyboardKey_KEY_F3, KeyboardKey_KEY_F4,
    KeyboardKey_KEY_F5, KeyboardKey_KEY_F6, KeyboardKey_KEY_F7, KeyboardKey_KEY_F8,
    KeyboardKey_KEY_F9, KeyboardKey_KEY_F10, KeyboardKey_KEY_F11, KeyboardKey_KEY_F12,
    KeyboardKey_KEY_FIVE, KeyboardKey_KEY_FOUR, KeyboardKey_KEY_G, KeyboardKey_KEY_GRAVE,
    KeyboardKey_KEY_H, KeyboardKey_KEY_HOME, KeyboardKey_KEY_I, KeyboardKey_KEY_INSERT,
    KeyboardKey_KEY_J, KeyboardKey_KEY_K, KeyboardKey_KEY_KB_MENU, KeyboardKey_KEY_KP_0,
    KeyboardKey_KEY_KP_1, KeyboardKey_KEY_KP_2, KeyboardKey_KEY_KP_3, KeyboardKey_KEY_KP_4,
    KeyboardKey_KEY_KP_5, KeyboardKey_KEY_KP_6, KeyboardKey_KEY_KP_7, KeyboardKey_KEY_KP_8,
    KeyboardKey_KEY_KP_9, KeyboardKey_KEY_KP_ADD, KeyboardKey_KEY_KP_DECIMAL,
    KeyboardKey_KEY_KP_DIVIDE, KeyboardKey_KEY_KP_ENTER, KeyboardKey_KEY_KP_EQUAL,
    KeyboardKey_KEY_KP_MULTIPLY, KeyboardKey_KEY_KP_SUBTRACT, KeyboardKey_KEY_L,
    KeyboardKey_KEY_LEFT, KeyboardKey_KEY_LEFT_ALT, KeyboardKey_KEY_LEFT_BRACKET,
    KeyboardKey_KEY_LEFT_CONTROL, KeyboardKey_KEY_LEFT_SHIFT, KeyboardKey_KEY_LEFT_SUPER,
    KeyboardKey_KEY_M, KeyboardKey_KEY_MENU, KeyboardKey_KEY_MINUS, KeyboardKey_KEY_N,
    KeyboardKey_KEY_NINE, KeyboardKey_KEY_NULL, KeyboardKey_KEY_NUM_LOCK, KeyboardKey_KEY_O,
    KeyboardKey_KEY_ONE, KeyboardKey_KEY_P, KeyboardKey_KEY_PAGE_DOWN, KeyboardKey_KEY_PAGE_UP,
    KeyboardKey_KEY_PAUSE, KeyboardKey_KEY_PERIOD, KeyboardKey_KEY_PRINT_SCREEN, KeyboardKey_KEY_Q,
    KeyboardKey_KEY_R, KeyboardKey_KEY_RIGHT, KeyboardKey_KEY_RIGHT_ALT,
    KeyboardKey_KEY_RIGHT_BRACKET, KeyboardKey_KEY_RIGHT_CONTROL, KeyboardKey_KEY_RIGHT_SHIFT,
    KeyboardKey_KEY_RIGHT_SUPER, KeyboardKey_KEY_S, KeyboardKey_KEY_SCROLL_LOCK,
    KeyboardKey_KEY_SEMICOLON, KeyboardKey_KEY_SEVEN, KeyboardKey_KEY_SIX, KeyboardKey_KEY_SLASH,
    KeyboardKey_KEY_SPACE, KeyboardKey_KEY_T, KeyboardKey_KEY_TAB, KeyboardKey_KEY_THREE,
    KeyboardKey_KEY_TWO, KeyboardKey_KEY_U, KeyboardKey_KEY_UP, KeyboardKey_KEY_V,
    KeyboardKey_KEY_VOLUME_DOWN, KeyboardKey_KEY_VOLUME_UP, KeyboardKey_KEY_W, KeyboardKey_KEY_X,
    KeyboardKey_KEY_Y, KeyboardKey_KEY_Z, KeyboardKey_KEY_ZERO, Vector2,
  },
  std::ffi::c_int,
};

#[derive(Clone)]
pub enum KeyboardKey {
  Null,
  Apostrophe,
  Comma,
  Minus,
  Period,
  Slash,
  Zero,
  One,
  Two,
  Three,
  Four,
  Five,
  Six,
  Seven,
  Eight,
  Nine,
  Semicolon,
  Equal,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  LeftBracket,
  Backslash,
  RightBracket,
  Grave,
  Space,
  Escape,
  Enter,
  Tab,
  Backspace,
  Insert,
  Delete,
  Right,
  Left,
  Down,
  Up,
  PageUp,
  PageDown,
  Home,
  End,
  CapsLock,
  ScrollLock,
  NumLock,
  PrintScreen,
  Pause,
  F1,
  F2,
  F3,
  F4,
  F5,
  F6,
  F7,
  F8,
  F9,
  F10,
  F11,
  F12,
  LeftShift,
  LeftControl,
  LeftAlt,
  LeftSuper,
  RightShift,
  RightControl,
  RightAlt,
  RightSuper,
  KbMenu,
  Kp0,
  Kp1,
  Kp2,
  Kp3,
  Kp4,
  Kp5,
  Kp6,
  Kp7,
  Kp8,
  Kp9,
  KpDecimal,
  KpDivide,
  KpMultiply,
  KpSubtract,
  KpAdd,
  KpEnter,
  KpEqual,
  Back,
  Menu,
  VolumeUp,
  VolumeDown,
  Other(u32),
}

#[derive(Clone)]
enum MouseButton {
  Left,
  Right,
  Middle,
  Side,
  Extra,
  Forward,
  Back,
}

impl From<KeyboardKey> for u32 {
  fn from(value: KeyboardKey) -> Self {
    use KeyboardKey::*;
    match value {
      Null => KeyboardKey_KEY_NULL,
      Apostrophe => KeyboardKey_KEY_APOSTROPHE,
      Comma => KeyboardKey_KEY_COMMA,
      Minus => KeyboardKey_KEY_MINUS,
      Period => KeyboardKey_KEY_PERIOD,
      Slash => KeyboardKey_KEY_SLASH,
      Zero => KeyboardKey_KEY_ZERO,
      One => KeyboardKey_KEY_ONE,
      Two => KeyboardKey_KEY_TWO,
      Three => KeyboardKey_KEY_THREE,
      Four => KeyboardKey_KEY_FOUR,
      Five => KeyboardKey_KEY_FIVE,
      Six => KeyboardKey_KEY_SIX,
      Seven => KeyboardKey_KEY_SEVEN,
      Eight => KeyboardKey_KEY_EIGHT,
      Nine => KeyboardKey_KEY_NINE,
      Semicolon => KeyboardKey_KEY_SEMICOLON,
      Equal => KeyboardKey_KEY_EQUAL,
      A => KeyboardKey_KEY_A,
      B => KeyboardKey_KEY_B,
      C => KeyboardKey_KEY_C,
      D => KeyboardKey_KEY_D,
      E => KeyboardKey_KEY_E,
      F => KeyboardKey_KEY_F,
      G => KeyboardKey_KEY_G,
      H => KeyboardKey_KEY_H,
      I => KeyboardKey_KEY_I,
      J => KeyboardKey_KEY_J,
      K => KeyboardKey_KEY_K,
      L => KeyboardKey_KEY_L,
      M => KeyboardKey_KEY_M,
      N => KeyboardKey_KEY_N,
      O => KeyboardKey_KEY_O,
      P => KeyboardKey_KEY_P,
      Q => KeyboardKey_KEY_Q,
      R => KeyboardKey_KEY_R,
      S => KeyboardKey_KEY_S,
      T => KeyboardKey_KEY_T,
      U => KeyboardKey_KEY_U,
      V => KeyboardKey_KEY_V,
      W => KeyboardKey_KEY_W,
      X => KeyboardKey_KEY_X,
      Y => KeyboardKey_KEY_Y,
      Z => KeyboardKey_KEY_Z,
      LeftBracket => KeyboardKey_KEY_LEFT_BRACKET,
      Backslash => KeyboardKey_KEY_BACKSLASH,
      RightBracket => KeyboardKey_KEY_RIGHT_BRACKET,
      Grave => KeyboardKey_KEY_GRAVE,
      Space => KeyboardKey_KEY_SPACE,
      Escape => KeyboardKey_KEY_ESCAPE,
      Enter => KeyboardKey_KEY_ENTER,
      Tab => KeyboardKey_KEY_TAB,
      Backspace => KeyboardKey_KEY_BACKSPACE,
      Insert => KeyboardKey_KEY_INSERT,
      Delete => KeyboardKey_KEY_DELETE,
      Right => KeyboardKey_KEY_RIGHT,
      Left => KeyboardKey_KEY_LEFT,
      Down => KeyboardKey_KEY_DOWN,
      Up => KeyboardKey_KEY_UP,
      PageUp => KeyboardKey_KEY_PAGE_UP,
      PageDown => KeyboardKey_KEY_PAGE_DOWN,
      Home => KeyboardKey_KEY_HOME,
      End => KeyboardKey_KEY_END,
      CapsLock => KeyboardKey_KEY_CAPS_LOCK,
      ScrollLock => KeyboardKey_KEY_SCROLL_LOCK,
      NumLock => KeyboardKey_KEY_NUM_LOCK,
      PrintScreen => KeyboardKey_KEY_PRINT_SCREEN,
      Pause => KeyboardKey_KEY_PAUSE,
      F1 => KeyboardKey_KEY_F1,
      F2 => KeyboardKey_KEY_F2,
      F3 => KeyboardKey_KEY_F3,
      F4 => KeyboardKey_KEY_F4,
      F5 => KeyboardKey_KEY_F5,
      F6 => KeyboardKey_KEY_F6,
      F7 => KeyboardKey_KEY_F7,
      F8 => KeyboardKey_KEY_F8,
      F9 => KeyboardKey_KEY_F9,
      F10 => KeyboardKey_KEY_F10,
      F11 => KeyboardKey_KEY_F11,
      F12 => KeyboardKey_KEY_F12,
      LeftShift => KeyboardKey_KEY_LEFT_SHIFT,
      LeftControl => KeyboardKey_KEY_LEFT_CONTROL,
      LeftAlt => KeyboardKey_KEY_LEFT_ALT,
      LeftSuper => KeyboardKey_KEY_LEFT_SUPER,
      RightShift => KeyboardKey_KEY_RIGHT_SHIFT,
      RightControl => KeyboardKey_KEY_RIGHT_CONTROL,
      RightAlt => KeyboardKey_KEY_RIGHT_ALT,
      RightSuper => KeyboardKey_KEY_RIGHT_SUPER,
      KbMenu => KeyboardKey_KEY_KB_MENU,
      Kp0 => KeyboardKey_KEY_KP_0,
      Kp1 => KeyboardKey_KEY_KP_1,
      Kp2 => KeyboardKey_KEY_KP_2,
      Kp3 => KeyboardKey_KEY_KP_3,
      Kp4 => KeyboardKey_KEY_KP_4,
      Kp5 => KeyboardKey_KEY_KP_5,
      Kp6 => KeyboardKey_KEY_KP_6,
      Kp7 => KeyboardKey_KEY_KP_7,
      Kp8 => KeyboardKey_KEY_KP_8,
      Kp9 => KeyboardKey_KEY_KP_9,
      KpDecimal => KeyboardKey_KEY_KP_DECIMAL,
      KpDivide => KeyboardKey_KEY_KP_DIVIDE,
      KpMultiply => KeyboardKey_KEY_KP_MULTIPLY,
      KpSubtract => KeyboardKey_KEY_KP_SUBTRACT,
      KpAdd => KeyboardKey_KEY_KP_ADD,
      KpEnter => KeyboardKey_KEY_KP_ENTER,
      KpEqual => KeyboardKey_KEY_KP_EQUAL,
      Back => KeyboardKey_KEY_BACK,
      Menu => KeyboardKey_KEY_MENU,
      VolumeUp => KeyboardKey_KEY_VOLUME_UP,
      VolumeDown => KeyboardKey_KEY_VOLUME_DOWN,
      Other(value) => value,
    }
  }
}

pub fn is_key_down(key: KeyboardKey) -> bool {
  unsafe { IsKeyDown(u32::from(key) as c_int) }
}

pub fn is_mouse_wheel_moving() -> bool {
  let wheel_move = unsafe { GetMouseWheelMove() };
  wheel_move < -0.01 || wheel_move > 0.01
}

pub fn is_mouse_wheel_moving_y() -> bool {
  let wheel_move = get_mouse_wheel_move_y();
  wheel_move < -0.01 || wheel_move > 0.01
}

pub fn get_mouse_wheel_move() -> Vector2 {
  unsafe { GetMouseWheelMoveV() }
}

pub fn get_mouse_wheel_move_y() -> f32 {
  get_mouse_wheel_move().y
}
